# Generated by Django 5.0.4 on 2024-04-15 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movietogenre',
            old_name='Genre_id',
            new_name='Genre',
        ),
        migrations.RenameField(
            model_name='movietogenre',
            old_name='Movie_id',
            new_name='Movie',
        ),
        migrations.RenameField(
            model_name='movieuserrating',
            old_name='Movie_id',
            new_name='Movie',
        ),
    ]
