# Generated by Django 5.0.4 on 2024-04-16 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_genre_id_movietogenre_genre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='movietogenre',
            old_name='Genre',
            new_name='genre',
        ),
        migrations.RenameField(
            model_name='movietogenre',
            old_name='Movie',
            new_name='movie',
        ),
        migrations.AddField(
            model_name='movie',
            name='Poster',
            field=models.TextField(default='img'),
        ),
        migrations.AddField(
            model_name='movie',
            name='length',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='MovieToActor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.actor')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.movie')),
            ],
        ),
        migrations.CreateModel(
            name='MovieToDirector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.movie')),
                ('wactor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.director')),
            ],
        ),
        migrations.CreateModel(
            name='MovieToWriter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.movie')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.writer')),
            ],
        ),
    ]
