# Generated by Django 5.0.4 on 2024-04-16 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_movie_released_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movietodirector',
            old_name='wactor',
            new_name='director',
        ),
        migrations.RenameField(
            model_name='movietolanguage',
            old_name='writer',
            new_name='language',
        ),
    ]
