# Generated by Django 5.0.4 on 2024-04-16 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_actor_name_alter_genre_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hall',
            name='created_at',
        ),
    ]
