# Generated by Django 5.0.4 on 2024-04-16 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_hall_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieschedule',
            name='hall',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.hall'),
        ),
    ]
