# Generated by Django 5.0.4 on 2024-04-16 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_movieschedule_hall'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movieschedule',
            name='hall',
        ),
        migrations.AddField(
            model_name='movieschedule',
            name='location',
            field=models.TextField(default='AKRS'),
        ),
        migrations.AddField(
            model_name='movieschedule',
            name='seat_count',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.DeleteModel(
            name='Hall',
        ),
    ]
