# Generated by Django 5.0.4 on 2024-04-17 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_movieschedule_hall_movieschedule_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieschedule',
            name='seat_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isPremium', models.BooleanField(default=False)),
                ('isAvailable', models.BooleanField(default=True)),
                ('schedule_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.movieschedule')),
            ],
        ),
    ]
