# Generated by Django 5.0.4 on 2024-04-17 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='movie_schedule',
        ),
        migrations.AddField(
            model_name='ticket',
            name='schedule',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.movieschedule'),
        ),
    ]
