# Generated by Django 5.0.4 on 2024-04-17 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_ticket_movie_schedule_ticket_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='number',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
