# Generated by Django 5.0.4 on 2024-04-17 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_comment_reply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Movie',
            new_name='movie',
        ),
        migrations.AlterField(
            model_name='comment',
            name='dislikes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
